/**
 * magister api
 * api for magister
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface EResult {
  'data'?: any;
  'success'?: boolean;
  'errorMessage'?: string;
  'exception'?: any;
}

