/**
 * magister api
 * api for magister
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface LemmaData {
  'lemmaId'?: number;
  'partOfSpeechId'?: number;
  'categoryId'?: number;
  'genderId'?: number;
  'useSingular'?: boolean;
  'category'?: models.Category;
  'gender'?: models.Genders;
  'lemma'?: models.Lemmas;
  'partOfSpeech'?: models.PartOfSpeech;
}

