/**
 * magister api
 * api for magister
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface List {
  'listId'?: number;
  'name'?: string;
  'description'?: string;
  'listOwners'?: Array<models.ListOwner>;
  'sections'?: Array<models.Section>;
}

